<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net6.0</TargetFramework>
		<Platforms>x64</Platforms>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<!-- 输出到启动器目录 -->
		<OutputPath>..\Launcher\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
		<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Lib.Harmony" Version="2.4.2" />
	</ItemGroup>

	<ItemGroup>
	  <Reference Include="Lawn">
	    <HintPath>..\..\WP_PGVZ\PlantGirlsVsZombies\Lawn.dll</HintPath>
	  </Reference>
	  <Reference Include="MonoGame.Framework">
	    <HintPath>..\..\WP_PGVZ\PlantGirlsVsZombies\MonoGame.Framework.dll</HintPath>
	  </Reference>
	</ItemGroup>

	<Import Project="..\pLawnModLoader_Shared\pLawnModLoader_Shared.projitems" Label="Shared" />

</Project>